import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';

import '../../features/groups/domain/entities/group.dart';
import '../../features/settlement/domain/entities/settlement.dart';
import '../constants/app_constants.dart';

/// Service for sharing settlement summaries.
///
/// Formats the settlement data as readable text and
/// triggers the platform share sheet via share_plus.
class ShareService {
  const ShareService();

  /// Shares the full settlement summary for a group.
  ///
  /// Opens the platform share sheet with formatted text
  /// that can be sent via WhatsApp, SMS, email, etc.
  Future<void> shareSettlementSummary({
    required Group group,
    required Map<String, double> netBalances,
    required List<Settlement> settlements,
    required double totalExpenses,
  }) async {
    final text = _formatSummary(
      group: group,
      netBalances: netBalances,
      settlements: settlements,
      totalExpenses: totalExpenses,
    );

    await SharePlus.instance.share(
      ShareParams(
        text: text,
        subject: 'Splity — ${group.name} Settlement Summary',
      ),
    );
  }

  /// Formats the settlement data as a readable string.
  String _formatSummary({
    required Group group,
    required Map<String, double> netBalances,
    required List<Settlement> settlements,
    required double totalExpenses,
  }) {
    final buffer = StringBuffer();
    final dateFormatter = DateFormat('dd MMM yyyy');
    final now = DateTime.now();
    const currency = AppConstants.currency;

    // === HEADER ===
    buffer.writeln('💸 Splity — Settlement Summary');
    buffer.writeln('Group: ${group.name} ${group.emoji}');
    buffer.writeln('Date: ${dateFormatter.format(now)}');
    buffer.writeln(
      'Total Expenses: $currency${totalExpenses.toStringAsFixed(2)}',
    );
    buffer.writeln();

    // === NET BALANCES ===
    buffer.writeln('📊 Net Balances:');

    final sortedBalances =
        netBalances.entries.toList()
          ..sort((a, b) => b.value.compareTo(a.value));

    for (final entry in sortedBalances) {
      final name = entry.key;
      final balance = entry.value;

      if (balance > 0.01) {
        buffer.writeln(
          '  ✅ $name gets back $currency${balance.toStringAsFixed(2)}',
        );
      } else if (balance < -0.01) {
        buffer.writeln(
          '  🔴 $name owes $currency${balance.abs().toStringAsFixed(2)}',
        );
      } else {
        buffer.writeln('  ✓ $name is settled');
      }
    }

    buffer.writeln();

    // === SETTLEMENTS ===
    if (settlements.isEmpty) {
      buffer.writeln('🎉 All settled — no payments needed!');
    } else {
      buffer.writeln('💳 Payments to Make:');
      for (int i = 0; i < settlements.length; i++) {
        final s = settlements[i];
        buffer.writeln(
          '  ${i + 1}. ${s.fromMember} → ${s.toMember}: '
          '$currency${s.amount.toStringAsFixed(2)}',
        );
      }

      final total = settlements.fold<double>(0, (sum, s) => sum + s.amount);
      buffer.writeln();
      buffer.writeln('Total to settle: $currency${total.toStringAsFixed(2)}');
    }

    buffer.writeln();
    buffer.writeln('─────────────────────');
    buffer.writeln('Generated by Splity 💸');

    return buffer.toString();
  }
}
